### ISSUE TITLE
Next & Previous for viewing cards

### ISSUE THREAD

**Issue by Enhaloed** [Force-of-Wind/fowsim#46]
E.g. when viewing GOG001 next goes to GOG002 and back goes to previous sets last card

**Comment by Enhaloed** [comment]
Somewhere at the bottom of the view_card.html page we should add buttons for "next" and "previous".

In views.py under view_card() you'll want to check if cards exist with the ID of +1 and -1 from the current card.

e.g. if the current card's card_id is 'GOG-91' then you should check to see if 'GOG-90' and 'GOG-92' exist, if so add a 'next' and/or 'previous' button with links to those pages. There are some niche cases with IDs where they can end with 'J' or '^', so you'll need to check for those.

'J' ending means it's the J-ruler (or otherwise backside of a ruler) of the same set code. E.g. GOG-079 is Loki's Ruler side and GOG-079J is the Order side. 

See:
https://www.forceofwind.online/card/GOG-079/
https://www.forceofwind.online/card/GOG-079J/

'^' means the alternative side of a card, e.g. flourishing hope + burgeoning despair. (It's printed as * on some cards but you can't save file names with *s in them so we use ^ internally)

**Comment by Zaloog** [comment]
Wouldnt it be better to refer to "next" as the "next card of the search" instead of "next card of the set"?

For example, if I search for 1 cost resonators and start with card no.1, the next button should bring me to card no.2 of my search results, instead of the next card from the set, which could be a chant for example.

**Comment by heihachi** [comment]
> Wouldnt it be better to refer to "next" as the "next card of the search" instead of "next card of the set"?
> 
> For example, if I search for 1 cost resonators and start with card no.1, the next button should bring me to card no.2 of my search results, instead of the next card from the set, which could be a chant for example.

I think for that to work we would need to remember the search results when going to the card details page, OR we can have the card detail page come up in a floating iframe or something and have the next and previous arrows on the side.

The latter is think would be better and would look and feel better when looking at cards for a deck

**Comment by edmundchan8** [comment]
I'll give this a crack, realised I need to spend time learning python more

So far, I'm thinking maybe adding the 'buttons' in the card_details.html file instead? (tbh, still inexperienced with python so probably wrong).

Access to the set acronyms/id and their correct order seems essential too (i.e. assault into the demonic world to the seventh, would need a check to from:

if next card in ADW != null
Get next set id  // (TST), from an array that holds all the sets in order?
next card id = TST-001
prev card id = ADW-099

**Comment by Enhaloed** [comment]
I think card_details is probably the best place for it. If you look inside view_card.html there's some logic there already for checking if we're at the last "card" on a given page to show decklists (It treats each side of the 2/3-sided cards as an individual card) and then pass in the information needed for next/prev cards via here.

We do need to work out what "next card" actually means though. Do we just want "next" card of ABC-100 to be ABC-101 and "previous" to be ABC-099 or should it be the "next in the search that got you here".

I think for the sake of consistency next/prev should just go by set code and be unrelated to the search that got them there since you can also get to cards without searching (e.g. discord bot or clicking on a decklist card).

In that case you may find it useful to check out sort_cards in cardDatabase/views.py
When showing a card we could do a search for cards in the same set, sort via sort_cards and then get the next/previous cards within a set when sorting by set code. 

Again, possibly up to you with the implementation how next/previous would work when showing the first card of a set. To avoid bad performance I don't think we want to lazily just sort by every set with every card because it would likely slow things down but maybe we could be cleverer about it if you wanted to (there is a list of the SETS_IN_ORDER in constants.py). Otherwise we could just gray the button out when it's the first/last card in a set.

Of course @ me in discord if you want help along the way too if that's easier
