### ISSUE TITLE
Poor search performance with long queries

### ISSUE THREAD

**Issue by Kossetsoup** [Force-of-Wind/fowsim#90]
Long text queries performed in modes such as 'Contains All' take a very long time to perform on the remote server. The query 'You may play this card from your removed area.' takes so long to perform that the Heroku worker times out (after working for 30 seconds).

This is likely associated with the large number of `Q` objects created related to this query -- consolidating these into fewer `Q` objects will likely improve performance.

**Comment by Enhaloed** [comment]
Also note of a bug in case the code from the previous commit (https://github.com/Force-of-Wind/fowsim/commit/7d6640c3f743a82b40028abce56aa4429dee356e) gets used later: it should be 'races__name' in search_fields instead of 'races'

**Comment by Enhaloed** [comment]
Closing this since the performance is ok now, will reopen a ticket about optimisations and maybe adding races back to basic search
